---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbmeta
  namespace: dev
  labels:
    app: fbapp
    env: dev
spec:
  selector:
    matchLabels:
      app: fb
      env: dev
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fb
        env: dev
        version: V1_AC
    spec:
      containers:
        - name: fbcont
          image: kalyan3546/class7:multistage
          ports:
            - containerPort: 8080
