
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metafb
  namespace: kalyanns
  labels:
    app: fb
spec:
  selector:
    matchLabels:
      app: facebook
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: facebook
        version: v1_AC
    spec:
      containers:
        - name: fbcont
          image: kalyan3546/class5:python_app
          ports:
            - containerPort: 8080
