

---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: votingapp
    name: votingser
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: votingapp
    name: voting
 


